Nikko's Daily Messing Around
Floof-Station/Floof-Station pull request #110
Opened 2024-08-15 18:22 UTC by Memeji

# Description

Added a pink collar and coder arm warmers to the vendors and loadout.

---

# Changelog

:cl:
- add: Pink Collar to Clothesmate and Loadout
- add: Coder Arm Warmers to Pride-O-Mat and Loadout

2024-08-16 06:54 UTC, FoxxoTrystan requested changes
There changes that are not marked from the PR, like.

Is changes on LewdTraitSystem supose to be here?

2024-08-16 14:09 UTC, Memeji commented
> There changes that are not marked from the PR, like.
> 
> Is changes on LewdTraitSystem supose to be here?

No they are not, those changes are not supposed to be here and will need to be removed. Do I just delete the file from this PR?

2024-08-16 15:05 UTC, FoxxoTrystan commented
> > There changes that are not marked from the PR, like.
> > Is changes on LewdTraitSystem supose to be here?
> 
> No they are not, those changes are not supposed to be here and will need to be removed. Do I just delete the file from this PR?

just edit the changes like they are currently on Master, deleting file will **DELETE FILE**

2024-08-16 16:17 UTC, Memeji commented
Removed changes to lewdtraitsystem and the lewd components.

2024-08-17 13:24 UTC, FoxxoTrystan requested changes

2024-08-17 17:35 UTC, Memeji commented on Resources/Prototypes/Floof/Traits/lewd.yml
Not part of this PR, no.

2024-08-17 18:56 UTC, FoxxoTrystan commented on Resources/Prototypes/Floof/Traits/lewd.yml
But those changes are here, should that change not be removed?

2024-08-17 20:13 UTC, FoxxoTrystan commented on Resources/Prototypes/Floof/Traits/lewd.yml
This PR still change the file name/location, no?

2024-08-18 21:19 UTC, FoxxoTrystan commented
Stale

2024-08-18 21:19 UTC, closed without merging