Disable hunger mechanic for now
Floof-Station/Floof-Station pull request #113
Opened 2024-08-16 03:56 UTC by Memeji

# Description

Disables the hunger inducing part of the code temporarily until a proper check is in place for if the solution is filled.

---

# Changelog

:cl:
- tweak: Cum/Milk regeneration doesn't use hunger.

2024-08-16 04:32 UTC, ShatteredSwords commented
Doesn't look like the error is legit, would consider retrying the build and test @FoxxoTrystan

2024-08-17 04:28 UTC, Memeji commented
Looking to have this reviewed sometime soon. As there's an issue with hunger right now.

2024-08-17 13:20 UTC, ShadesMars requested changes

2024-08-17 17:35 UTC, Memeji commented on Content.Server/FloofStation/Traits/LewdTraitSystem.cs
> -
So I'm confused here, tell me if my logic is incorrect but:
if the mob is NOT dead, exit the function and DO NOT add the reagent to the container.

Isn't this what would happen?

2024-08-17 17:35 UTC, Memeji commented on Content.Server/FloofStation/Traits/LewdTraitSystem.cs
> -
So I'm confused here, tell me if my logic is incorrect but:
if the mob is NOT dead, exit the function and DO NOT add the reagent to the container.

Isn't this what would happen?

2024-08-17 18:54 UTC, FoxxoTrystan commented on Content.Server/FloofStation/Traits/LewdTraitSystem.cs
> -
_mobState.IsDead() = check if dead.
continue = continue.

Right now you checking if its dead, if yes continue.

2024-08-17 18:54 UTC, FoxxoTrystan commented on Content.Server/FloofStation/Traits/LewdTraitSystem.cs
> -
> So I'm confused here, tell me if my logic is incorrect but: if the mob is NOT dead, exit the function and DO NOT add the reagent to the container.
> 
> Isn't this what would happen?

oh wait is it that?

2024-08-17 18:56 UTC, FoxxoTrystan commented on Content.Server/FloofStation/Traits/LewdTraitSystem.cs
> -
Should i be not if not dead continue?

2024-08-17 20:19 UTC, FoxxoTrystan requested changes

2024-08-17 20:19 UTC, FoxxoTrystan commented on Content.Server/FloofStation/Traits/LewdTraitSystem.cs
> -
This need to be reverted, add it back.

2024-08-17 20:19 UTC, FoxxoTrystan commented on Content.Server/FloofStation/Traits/LewdTraitSystem.cs
> -
This need to be reverted, add it back.

2024-08-17 23:21 UTC, FoxxoTrystan approved these changes

2024-08-17 23:21 UTC, merged